-- Script de cria��o do banco (SQLite). Executado em runtime por uDM.CriarEstruturaBanco.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS TIPO_PESSOA (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRICAO   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PESSOA (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_TIPO_PESSOA      INTEGER NOT NULL,
    NOME                VARCHAR(150) NOT NULL,
    DATA_NASCIMENTO     DATE,
    CPF                 VARCHAR(14) NOT NULL UNIQUE,
    RG                  VARCHAR(20),
    EMAIL               VARCHAR(120),
    TELEFONE            VARCHAR(20),
    CRIADO_EM           DATETIME DEFAULT CURRENT_TIMESTAMP,
    ATUALIZADO_EM       DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PESSOA_TIPO
        FOREIGN KEY (ID_TIPO_PESSOA)
        REFERENCES TIPO_PESSOA(ID)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ENDERECO (
    ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PESSOA       INTEGER NOT NULL UNIQUE,
    CEP             VARCHAR(9),
    LOGRADOURO      VARCHAR(150),
    NUMERO          VARCHAR(20),
    COMPLEMENTO     VARCHAR(100),
    BAIRRO          VARCHAR(100),
    CIDADE          VARCHAR(100),
    ESTADO          CHAR(2),
    CONSTRAINT FK_ENDERECO_PESSOA
        FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID)
        ON DELETE CASCADE
);

INSERT OR IGNORE INTO TIPO_PESSOA (DESCRICAO) VALUES ('Cliente');
INSERT OR IGNORE INTO TIPO_PESSOA (DESCRICAO) VALUES ('Fornecedor');
INSERT OR IGNORE INTO TIPO_PESSOA (DESCRICAO) VALUES ('Funcionário');

CREATE INDEX IF NOT EXISTS IDX_PESSOA_NOME ON PESSOA(NOME);
CREATE INDEX IF NOT EXISTS IDX_PESSOA_TIPO ON PESSOA(ID_TIPO_PESSOA);
